# syntax=docker/dockerfile:1
FROM Alpine:latest
WORKDIR /
ENV PYTHONUNBUFFERED=1

# OCR Watchdog environement variable
ENV OCR_OUTPUT_DIRECTORY_YEAR_MONTH=0
ENV OCR_ON_SUCCESS_ARCHIVE=0
ENV OCR_DESKEW=1
ENV OCR_ON_SUCCESS_DELETE=1

# Python&pip dependency
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip install watchdog pdfminer.six pikepdf ocrmypdf
COMMANDE run.sh