version: '3'

services:
  renamer:
    build:
      context: .
      dockerfile: ./dockerfile.renamer
    command: python3 ./RenameMyPDF.py
    volumes:
      - ./ocr-output:/ocr-output
      - ./final-output:/final-output

  watcher:
    build:
      context: .
      dockerfile: ./dockerfile.ocr
    command: python3 ./watcher.py
    volumes:
      - ./scan-input:/scan-input
      - ./ocr-output:/ocr-output
    env_file:
     - ./.env
