FROM ubuntu:23.04
RUN apt -y update && apt -y upgrade
RUN apt -y install python3 python3-watchdog python3-pdfminer
RUN apt-get -y autoclean
COPY run-renamer.sh run-renamer.sh
COPY RenameMyPDF.py RenameMyPDF.py
RUN useradd -ms /bin/bash -u 1026 -g 100 user123
USER user123
ENTRYPOINT ["/bin/bash"]