Sending build context to Docker daemon  6.687MB
Step 1/20 : FROM alpine:latest
 ---> b2aa39c304c2
Step 2/20 : ENV PYTHONUNBUFFERED: "1"
 ---> Using cache
 ---> 27928c909641
Step 3/20 : ENV OCR_INPUT_DIRECTORY: "scan-input"
 ---> Using cache
 ---> c67a0f67df33
Step 4/20 : ENV OCR_OUTPUT_DIRECTORY: "ocr-output"
 ---> Using cache
 ---> 760ed2ad8dcb
Step 5/20 : ENV OCR_OUTPUT_DIRECTORY_YEAR_MONTH: "0"
 ---> Using cache
 ---> 02d8e68898be
Step 6/20 : ENV OCR_ON_SUCCESS_ARCHIVE: "0"
 ---> Using cache
 ---> 7f9092f1d19e
Step 7/20 : ENV OCR_DESKEW: "1"
 ---> Using cache
 ---> 7ef96842a2ab
Step 8/20 : ENV OCR_ON_SUCCESS_DELETE: "1"
 ---> Using cache
 ---> e0beff683a16
Step 9/20 : ENV OCR_JSON_SETTINGS: '{"rotate_pages": true, "skip_text": true, "language": "eng+fra", "output_type":"pdf"}'
 ---> Using cache
 ---> 41c63e2e0bf5
Step 10/20 : ENV C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/freetype2
 ---> Using cache
 ---> fcbe92db36c0
Step 11/20 : RUN apt install --update --no-cache python3 python3-dev tesseract-ocr tesseract-ocr-data-fra tesseract-ocr-data-deu ghostscript qpdf-dev build-base py3-pybind11-dev freetype-dev && ln -sf python3 /usr/bin/python
 ---> Running in a7b653a95dd7
[91m/bin/sh: apt: not found
[0m