FROM ubuntu:23.04
ENV PYTHONUNBUFFERED: "1"
RUN apt -y update && apt -y upgrade
RUN apt -y install python3 python3-watchdog python3-pdfminer
RUN apt-get -y autoclean
COPY run-renamer.sh run-renamer.sh
COPY RenameMyPDF.py RenameMyPDF.py
ENTRYPOINT ["/bin/bash"]
CMD ["python3 RenameMyPDF.py"]