FROM ubuntu:23.04
RUN apt -y update && apt -y upgrade
RUN apt -y install python3 python3-watchdog python3-pdfminer ocrmypdf tesseract-ocr-fra tesseract-ocr-deu
RUN apt-get -y autoclean
COPY run-watcher.sh run-watcher.sh
COPY watcher.py watcher.py
RUN useradd -ms /bin/bash -u 1026 -g 100 user123
USER user123
ENTRYPOINT ["/bin/bash"]