FROM archlinux:latest
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm python python-pip libimagequant
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install watchdog pdfminer.six
RUN pacman -Scc --noconfirm
ENTRYPOINT ["/bin/bash"]
CMD ["python3 renamemypdf.py"]