version: '3'

services:
  renamer:
    build:
      context: .
      dockerfile: ./dockerfile.renamer
    command: run-renamer.sh
    volumes:
      - ./ocr-output:/ocr-output
      - ./final-output:/final-output

  ocr:
    build:
      context: .
      dockerfile: ./dockerfile.ocr
    command: run-watcher.sh
    volumes:
      - ./scan-input:/scan-input
      - ./ocr-output:/ocr-output
    env_file:
     - ./.env
