FROM ubuntu:latest
RUN apt -y update && apt -y upgrade
RUN apt -y install python3 python3-watchdog python3-pdfminer ocrmypdf tesseract-ocr-fra tesseract-ocr-deu
RUN apt-get -y autoclean
#
# Depending on the system on which this container is running, it may be necessary to configure
# this line in relation to an existing user on the OS.
#
# RUN chown 1026:100 watcher.py
ENTRYPOINT ["/bin/bash"]