# syntax=docker/dockerfile:1
version: "3.8"
services:
  app:
    container_name: "Dexel_PDF"
    image: alpine
    environment :
      PYTHONUNBUFFERED: "1"
      OCR_INPUT_DIRECTORY: "scan-input"
      OCR_OUTPUT_DIRECTORY: "ocr-output"
      OCR_OUTPUT_DIRECTORY_YEAR_MONTH: "0"
      OCR_ON_SUCCESS_ARCHIVE: "0"
      OCR_DESKEW: "1"
      OCR_ON_SUCCESS_DELETE: "1"
      OCR_JSON_SETTINGS: '{"rotate_pages": true, "skip_text": true, "language": "eng+fra", "output_type":"pdf"}'
    command: run.sh