FROM archlinux:latest
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm python python-pip tesseract tesseract-data-fra tesseract-data-deu tesseract-data-eng ghostscript
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install watchdog pdfminer.six ocrmypdf
RUN pacman -Scc --noconfirm
ENTRYPOINT ["/bin/bash"]