version: '3'

services:
  bl-ocr:
    build:
      context: .
    # Needed for matching user permission with host machine
    # You can use "id" command on linux terminal
    # "userID:groupeID"
    # user: 1032:100
    volumes:
    #
    # Input / Output folder location (NFS / Local)
    #   + Check "Volumes" bellow for NFS server details
    #   + Use of NFS need "Polling - true" in .env
    #
    # local
      - ./input:/app/input
      - ./processed:/app/processed
      - ./log:/app/log
    #
    # NFS
    #
    #   - input:/app/input
    #   - processed:/app/processed
    #   - log:/app/log
# volumes:
#   scan-input:
#     driver_opts:
#       type: "nfs"
#       o: "addr=192.168.45.29,nfsvers=4,sec=sys,proto=tcp"
#       device: ":/volume1/Docker/PDF-OCR-RENAME/input"
#   log:
#     driver_opts:
#       type: "nfs"
#       o: "addr=192.168.45.29,nfsvers=4,sec=sys,proto=tcp"
#       device: ":/volume1/Docker/PDF-OCR-RENAME/log"
#   final-output:
#     driver_opts:
#       type: "nfs"
#       o: "addr=192.168.45.29,nfsvers=4,sec=sys,proto=tcp"
#       device: ":/volume1/Docker/PDF-OCR-RENAME/output"